services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: brabank_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d brabank_auth"]
      interval: 5s
      timeout: 5s 
      retries: 10

  auth_service:
    build: ./auth/
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PSQL_DB_URL=jdbc:postgresql://db:5432/brabank_auth
      - PSQL_USER=postgres
      - PSQL_PW=postgres
    restart: always
    ports:
      - "8080:8080"
