spring.datasource.url=${PSQL_DB_URL:jdbc:postgresql://localhost:5432/brabank_auth}
spring.datasource.username=${PSQL_USER:postgres}
spring.datasource.password=${PSQL_PW:postgres}
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true